"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";

type ProductFormData={id?:string;name?:string;bearingNumber?:string;sku?:string;productType?:string;categorySlug?:string;brandSlug?:string;boreDiameter?:number|null;outsideDiameter?:number|null;width?:number|null;stockStatus?:string;status?:string;shortDescription?:string;seoTitle?:string;metaDescription?:string;version?:number};
export default function ProductForm({initial={}}:{initial?:ProductFormData}){
 const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const form=new FormData(e.currentTarget);const payload=Object.fromEntries(form);const url=initial.id?`/api/admin/products/${initial.id}`:"/api/admin/products";const response=await fetch(url,{method:initial.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,version:initial.version})});const data=await response.json() as {error?:string;id?:string};setSaving(false);if(!response.ok){setMessage(data.error??"Unable to save product.");return;}setMessage("Product saved successfully.");if(!initial.id&&data.id)location.href=`/admin/products/${data.id}`;}
 return <form className="admin-form" onSubmit={submit}><div className="admin-form-grid"><label>Product name<input name="name" required defaultValue={initial.name}/></label><label>Bearing / model number<input name="bearingNumber" required defaultValue={initial.bearingNumber}/></label><label>SKU<input name="sku" defaultValue={initial.sku}/></label><label>Product type<input name="productType" required defaultValue={initial.productType}/></label><label>Category slug<input name="categorySlug" required defaultValue={initial.categorySlug??"ball-bearings"}/></label><label>Brand slug<input name="brandSlug" defaultValue={initial.brandSlug??"nsk"}/></label><label>Bore diameter (mm)<input name="boreDiameter" type="number" min="0" step="1" defaultValue={initial.boreDiameter??""}/></label><label>Outside diameter (mm)<input name="outsideDiameter" type="number" min="0" step="1" defaultValue={initial.outsideDiameter??""}/></label><label>Width (mm)<input name="width" type="number" min="0" step="1" defaultValue={initial.width??""}/></label><label>Availability<select name="stockStatus" defaultValue={initial.stockStatus??"confirm_availability"}><option value="confirm_availability">Confirm Availability</option><option value="in_stock">In Stock</option><option value="limited_stock">Limited Stock</option><option value="available_on_order">Available on Order</option><option value="sourcing_available">Sourcing Available</option><option value="out_of_stock">Out of Stock</option><option value="discontinued">Discontinued</option></select></label><label>Publishing status<select name="status" defaultValue={initial.status??"draft"}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label></div><label>Short description<textarea name="shortDescription" rows={4} defaultValue={initial.shortDescription}/></label><fieldset><legend>Search information</legend><label>SEO title<input name="seoTitle" defaultValue={initial.seoTitle}/></label><label>Meta description<textarea name="metaDescription" rows={3} defaultValue={initial.metaDescription}/></label></fieldset>{message&&<p className="admin-form-message" role="status">{message}</p>}<div className="admin-form-actions"><Link href="/admin/products">Cancel</Link><button className="admin-primary" disabled={saving}>{saving?"Saving…":"Save product"}</button></div></form>;
}
