const sections = [
  ["1. Information We May Collect", ["Depending on how you interact with Bearing Mart BD, we may collect information such as:"], ["Name", "Company name", "Job title", "Telephone number", "WhatsApp number", "Email address", "Billing or delivery address", "Product enquiries", "Bearing numbers and specifications requested", "Quotation information", "Order and transaction information", "Communication history", "Information voluntarily submitted through website forms"], ["We may also automatically receive limited technical information when you visit our website, such as browser type, device type, IP address, pages visited, referring pages and general website usage information."]],
  ["2. How We Use Information", ["We may use information collected for purposes including:"], ["Responding to product enquiries", "Preparing quotations", "Processing and fulfilling orders", "Arranging delivery", "Providing customer support", "Communicating about orders and enquiries", "Identifying requested bearings and industrial products", "Maintaining business records", "Improving our website and services", "Preventing fraudulent or unauthorized activity", "Meeting applicable legal, accounting and regulatory requirements"], ["Where permitted, we may also use contact information to inform existing or prospective customers about relevant products, stock availability or business offers."]],
  ["3. WhatsApp, Telephone and Email Communications", ["If you contact Bearing Mart BD through WhatsApp, telephone, email or another communication platform, information you provide may be retained as part of our customer service and business records.", "Third-party communication services may process information according to their own privacy policies."]],
  ["4. Cookies and Website Analytics", ["Our website may use cookies and similar technologies to provide website functionality, understand website traffic and improve the visitor experience.", "We may also use third-party analytics or marketing services where appropriate.", "Visitors may be able to manage cookies through their browser settings or through any cookie-management options provided on our website."]],
  ["5. Google Services", ["Our website or business operations may use Google services such as Google Maps, Google Business Profile or website analytics.", "Information processed through these services may also be subject to Google's applicable privacy policies and terms."]],
  ["6. How We Share Information", ["Bearing Mart BD does not sell customers' personal information as a business practice.", "We may share necessary information with trusted service providers where required to conduct business, including:"], ["Delivery and courier companies", "Logistics providers", "Payment service providers", "Website hosting and technology providers", "Accounting or professional service providers", "Suppliers where necessary to fulfil a specific sourcing request", "Government or regulatory authorities where legally required"], ["We aim to disclose only information reasonably necessary for the relevant purpose."]],
  ["7. Payment Information", ["Where payments are processed through banks, mobile financial services, payment gateways or other third-party payment providers, those providers may process payment-related information according to their own terms and privacy policies.", "Bearing Mart BD should not intentionally store complete payment-card information unless appropriate systems and security requirements are implemented for that purpose."]],
  ["8. Data Security", ["We take reasonable administrative and technical measures to protect information against unauthorized access, loss, misuse, alteration or disclosure.", "However, no internet transmission, electronic communication or data-storage method can be guaranteed to be completely secure."]],
  ["9. Data Retention", ["We may retain customer and business information for as long as reasonably necessary to:"], ["Complete transactions", "Provide customer support", "Maintain purchase and warranty records", "Meet accounting requirements", "Resolve disputes", "Comply with applicable legal obligations"], ["Information that is no longer reasonably required may be deleted or securely disposed of according to our business practices and applicable requirements."]],
  ["10. Your Information", ["Subject to applicable law and verification of your identity, you may contact us regarding personal information we hold about you and request appropriate correction or deletion where applicable.", "Certain information may need to be retained for legal, accounting, transaction, fraud-prevention or legitimate business purposes."]],
  ["11. Third-Party Websites", ["Our website may contain links to manufacturers, suppliers, social media platforms or other third-party websites.", "Bearing Mart BD does not control and is not responsible for the privacy practices of those third parties. Visitors should review the privacy policies of external websites they use."]],
  ["12. Children's Privacy", ["Our website and industrial products are intended primarily for businesses, professionals and general adult customers.", "We do not knowingly seek to collect personal information from children through our business website."]],
  ["13. Changes to This Privacy Policy", ["We may update this Privacy Policy as our website, services, technologies or legal requirements change.", "The latest version will be published on this page with the updated revision date."]],
];
export default function PrivacyPage(){return <main className="terms-page"><header className="nav"><a className="brand" href="/">Bearing <span>Mart BD</span></a><nav><a href="/about">About</a><a href="/#products">Products</a><a href="/contact">Contact</a></nav><a className="nav-call" href="https://wa.me/8801914528336">WhatsApp Now</a></header><section className="terms-hero"><p className="eyebrow">LEGAL INFORMATION</p><h1>Privacy<br /><em>Policy.</em></h1><p>Last Updated: August 2026</p></section><section className="terms-content"><p className="terms-intro"><strong>Bearing Mart BD</strong> respects the privacy of our customers, website visitors, suppliers and business partners. This Privacy Policy explains how we may collect, use, store and protect information when you visit our website, contact us, request a quotation or purchase products from us.</p><p className="terms-intro">By using our website or voluntarily providing information to us, you acknowledge the practices described in this Privacy Policy.</p>{sections.map(([title,paragraphs,bullets,after])=><article className="terms-section" key={title as string}><h2>{title as string}</h2>{(paragraphs as string[]).map(p=><p key={p}>{p}</p>)}{bullets&&<ul>{(bullets as string[]).map(b=><li key={b}>{b}</li>)}</ul>}{after&&(after as string[]).map(p=><p key={p}>{p}</p>)}</article>)}<article className="terms-section"><h2>14. Contact Us</h2><p>If you have questions regarding this Privacy Policy or how Bearing Mart BD handles personal information, please contact:</p><address><strong>Bearing Mart BD</strong><br />2nd Floor, Siddique Machinery Market<br />10 Modonpal Lane<br />Dhaka 1100, Bangladesh<br /><br /><strong>Website:</strong> <a href="https://bearingmartbd.com">bearingmartbd.com</a><br /><br />You may also contact us using the official telephone, WhatsApp or email information published on our website.</address></article></section></main>}
