"use client";
import { useMemo, useState } from "react";
import type { CategoryProduct } from "./category-catalogue-data";

export default function CategoryCatalogBrowser({products,categorySlug}:{products:readonly CategoryProduct[];categorySlug:string}) {
  const [brand,setBrand] = useState("all"),[model,setModel] = useState(""),[type,setType] = useState("all");
  const brands = [...new Set(products.map(product => product.brand))];
  const types = [...new Set(products.map(product => product.type))];
  const visible = useMemo(() => products.filter(product => (brand === "all" || product.brand === brand) && (type === "all" || product.type === type) && `${product.model} ${product.type}`.toLowerCase().includes(model.toLowerCase())),[products,brand,model,type]);
  return <section className="shop-catalog"><aside className="catalog-filters"><p className="eyebrow">FIND PRODUCTS</p><h2>Search by model<br />or brand.</h2><label>1. Brand<select value={brand} onChange={event=>setBrand(event.target.value)}><option value="all">All available brands</option>{brands.map(item=><option key={item}>{item}</option>)}</select></label><label>2. Model No.<input value={model} onChange={event=>setModel(event.target.value)} placeholder="e.g. UCP 205" /></label><label>3. Type<select value={type} onChange={event=>setType(event.target.value)}><option value="all">All product types</option>{types.map(item=><option key={item}>{item}</option>)}</select></label><p className="filter-note">Availability is shown on each item. Confirm the exact brand, size and stock before ordering.</p></aside><div className="catalog-results"><div className="catalog-results-head"><p><strong>{visible.length}</strong> products found</p><span>{brand === "all" ? "All brands" : `Brand: ${brand}`}</span></div><div className="shop-grid">{visible.map(product=><article className="shop-card category-shop-card" key={`${product.brand}-${product.model}`}><div className="category-product-image"><img src={product.image} alt={`Representative ${product.type} product photograph`} loading="lazy" /><span>Representative product photo</span></div><p className="product-brand">{product.brand}</p><h3>{product.model}</h3><p>{product.type}</p><dl><div><dt>Availability</dt><dd>{product.availability}</dd></div><div><dt>Price</dt><dd>On request</dd></div></dl><a className="details-button" href={`/products/${categorySlug}/catalog/${product.slug}`}>View details →</a></article>)}</div>{visible.length===0&&<div className="empty-results"><h3>No matching product found.</h3><p>Try another brand, model number or type, or contact us for sourcing support.</p></div>}</div></section>;
}
