import { env } from "cloudflare:workers";
import bcrypt from "bcryptjs";

export const CUSTOMER_SESSION_COOKIE="__Host-bmbd_customer_session";
const ITERATIONS=210000,SESSION_SECONDS=60*60*24*7;
const encode=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes));
const decode=(value:string)=>Uint8Array.from(atob(value),character=>character.charCodeAt(0));

export async function hashPassword(password:string){return `bcrypt$${await bcrypt.hash(password,12)}`}
export async function verifyPassword(password:string,stored:string){if(stored.startsWith("bcrypt$"))return bcrypt.compare(password,stored.slice(7));const [algorithm,count,saltValue,expectedValue]=stored.split("$");if(algorithm!=="pbkdf2_sha256"||!count||!saltValue||!expectedValue)return false;const iterations=Number(count);if(!Number.isInteger(iterations)||iterations<100000||iterations>1000000)return false;try{const salt=decode(saltValue),expected=decode(expectedValue),key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]),actual=new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations},key,expected.length*8));if(actual.length!==expected.length)return false;let difference=0;for(let index=0;index<actual.length;index++)difference|=actual[index]^expected[index];return difference===0}catch{return false}}
export function validatePassword(password:string){return password.length>=10&&password.length<=128&&/[a-z]/.test(password)&&/[A-Z]/.test(password)&&/[0-9]/.test(password)}
export async function tokenHash(token:string){const bytes=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token)));return Array.from(bytes,value=>value.toString(16).padStart(2,"0")).join("")}
export async function createCustomerSession(customerId:string){const raw=encode(crypto.getRandomValues(new Uint8Array(32))).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");const id=await tokenHash(raw),now=new Date(),expires=new Date(now.getTime()+SESSION_SECONDS*1000);await env.DB.batch([env.DB.prepare("DELETE FROM customer_sessions WHERE customer_id=? OR expires_at<=?").bind(customerId,now.toISOString()),env.DB.prepare("INSERT INTO customer_sessions (id,customer_id,expires_at,created_at) VALUES (?,?,?,?)").bind(id,customerId,expires.toISOString(),now.toISOString())]);return {raw,maxAge:SESSION_SECONDS}}
export function sessionCookie(raw:string,maxAge:number){return `${CUSTOMER_SESSION_COOKIE}=${raw}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
export function readCookie(header:string|null,name:string){for(const part of (header??"").split(";")){const [key,...value]=part.trim().split("=");if(key===name)return value.join("=")}return null}
export async function getCustomerFromSession(cookieHeader:string|null){const raw=readCookie(cookieHeader,CUSTOMER_SESSION_COOKIE);if(!raw)return null;const id=await tokenHash(raw);return env.DB.prepare(`SELECT c.id,c.customer_type AS customerType,c.full_name AS fullName,c.company_name AS companyName,c.mobile,c.email,c.status,c.created_at AS createdAt,s.expires_at AS expiresAt FROM customer_sessions s JOIN customers c ON c.id=s.customer_id WHERE s.id=? AND s.expires_at>?`).bind(id,new Date().toISOString()).first<{id:string;customerType:string;fullName:string;companyName:string|null;mobile:string;email:string;status:string;createdAt:string;expiresAt:string}>()}
export async function deleteCustomerSession(cookieHeader:string|null){const raw=readCookie(cookieHeader,CUSTOMER_SESSION_COOKIE);if(raw)await env.DB.prepare("DELETE FROM customer_sessions WHERE id=?").bind(await tokenHash(raw)).run()}
