const sections = [
  { title: "1. About Bearing Mart BD", paragraphs: ["Bearing Mart BD is an importer, supplier and sourcing provider of industrial bearings, bearing housings, linear motion products, industrial accessories and related products in Bangladesh.", "Our website is designed to provide customers with information about our products and services and to facilitate product enquiries, quotation requests and business communication."] },
  { title: "2. Product Information", paragraphs: ["We make reasonable efforts to ensure that product names, bearing numbers, dimensions, specifications, descriptions, photographs and other information displayed on our website are accurate.", "However, product specifications may vary depending on the manufacturer, country of origin, production batch, design revision and product variant.", "Customers should confirm all critical technical specifications before placing an order.", "For industrial applications where dimensions, load ratings, speed ratings, clearance, tolerance, sealing, lubrication or other technical characteristics are critical, customers are responsible for confirming that the selected product is suitable for their intended application."] },
  { title: "3. Brands and Trademarks", paragraphs: ["Bearing Mart BD may supply products manufactured by various international and domestic manufacturers.", "All brand names, trademarks, logos and product names appearing on our website belong to their respective owners.", "The display or reference to a particular brand does not imply that Bearing Mart BD owns, controls or is officially affiliated with that brand unless such authorization or relationship is specifically stated.", "Product availability for individual brands may vary."] },
  { title: "4. Quotations and Prices", paragraphs: ["Prices displayed on the website, where applicable, may be subject to change without prior notice.", "For products marked “Request Quote,” “Contact for Price,” “Call for Price,” “On Request,” or similar, customers should contact Bearing Mart BD for the current price and availability.", "A quotation may specify its own validity period.", "Prices may change because of factors including supplier pricing, foreign exchange rates, import costs, freight charges, taxes, duties and market conditions.", "Unless otherwise specified, a quotation does not constitute a binding commitment to supply until the order has been accepted and any required payment has been received."] },
  { title: "5. Product Availability", paragraphs: ["Products displayed on our website are not necessarily available in stock at all times.", "Products may be:"], bullets: ["In Stock", "Limited Stock", "Available on Order", "Available through Sourcing", "Out of Stock", "Discontinued"], after: ["Customers are encouraged to confirm availability before making payment or finalizing an order."] },
  { title: "6. Orders", paragraphs: ["An order becomes confirmed after Bearing Mart BD accepts the order and any agreed advance or full payment has been received, where applicable.", "We reserve the right to decline or cancel an order in circumstances including pricing errors, incorrect product information, non-availability, suspected fraudulent transactions, payment issues or circumstances beyond our reasonable control.", "If payment has already been received for an order that we cannot fulfil, the applicable amount will be handled in accordance with the agreed refund arrangement."] },
  { title: "7. Payment", paragraphs: ["Available payment methods will be communicated to customers at the time of purchase or quotation.", "Customers must ensure that payments are made using the payment details officially provided by Bearing Mart BD.", "Bearing Mart BD will not be responsible for payments made to unauthorized persons, unofficial accounts or incorrect payment details that were not provided through our authorized communication channels."] },
  { title: "8. Delivery", paragraphs: ["Delivery times are estimates unless a specific delivery commitment has been agreed in writing.", "Delivery time may depend on stock availability, sourcing location, courier or transport arrangements, import procedures and the customer's delivery location.", "Customers are responsible for providing complete and accurate delivery information.", "Any visible damage, shortage or incorrect item should be reported to Bearing Mart BD as soon as reasonably possible after receiving the shipment."] },
  { title: "9. Inspection of Products", paragraphs: ["Customers should inspect products upon receipt and verify:"], bullets: ["Bearing number", "Brand", "Quantity", "Dimensions where applicable", "Seal or shield configuration", "Internal clearance where applicable", "Product condition", "Other order-specific requirements"], after: ["Products should not be installed or used if the customer believes that the product supplied is incorrect or damaged."] },
  { title: "10. Returns and Exchanges", paragraphs: ["Returns or exchanges are subject to Bearing Mart BD's applicable return policy and the condition of the supplied product.", "A return may be refused where a product has been installed, used, damaged, altered, contaminated, improperly stored, removed from sealed or manufacturer-specific packaging where resale is affected, or specially sourced/imported for a customer's order.", "Customers should contact us before returning any product.", "No product should be returned without prior approval from Bearing Mart BD."] },
  { title: "11. Warranty", paragraphs: ["Where a manufacturer's warranty applies, warranty coverage will generally be subject to the manufacturer's applicable terms and assessment.", "Warranty claims may require evidence of purchase, product photographs, packaging information, batch/serial information where applicable and details of the application in which the product was used.", "Warranty may not cover damage resulting from incorrect installation, improper lubrication, contamination, misalignment, excessive load, improper storage, misuse, modification or normal wear and tear."] },
  { title: "12. Technical Advice", paragraphs: ["Any product recommendation or technical information provided by Bearing Mart BD is intended to assist customers in product selection.", "Final responsibility for determining whether a particular bearing or industrial product is appropriate for a specific machine, operating environment or engineering application remains with the customer or responsible engineer/technician.", "Where safety or equipment reliability is critical, professional engineering assessment should be obtained before installation."] },
  { title: "13. Website Content", paragraphs: ["The content of this website, including text, layout, graphics, product organization and original materials produced by Bearing Mart BD, may not be copied, reproduced, republished or commercially exploited without our permission, except where permitted by applicable law.", "Third-party trademarks, manufacturer photographs, catalog information and specifications remain the property of their respective owners."] },
  { title: "14. Website Availability", paragraphs: ["We aim to keep our website available and accurate but cannot guarantee uninterrupted or error-free operation.", "We may modify, suspend, update or discontinue parts of the website without prior notice."] },
  { title: "15. Third-Party Links", paragraphs: ["Our website may contain links to third-party websites or services.", "Bearing Mart BD is not responsible for the content, security, privacy practices or availability of third-party websites."] },
  { title: "16. Limitation of Liability", paragraphs: ["To the extent permitted by applicable law, Bearing Mart BD will not be responsible for indirect or consequential losses resulting from misuse of products, incorrect product selection, improper installation, unauthorized modification, failure to follow manufacturer recommendations or circumstances outside our reasonable control.", "Nothing in these Terms & Conditions excludes or limits any rights or liabilities that cannot legally be excluded under applicable law."] },
  { title: "17. Privacy", paragraphs: ["Personal information submitted through our website is handled in accordance with our Privacy Policy."] },
  { title: "18. Changes to These Terms", paragraphs: ["Bearing Mart BD may revise these Terms & Conditions from time to time.", "The updated version will be published on this website with an updated revision date. Continued use of the website after changes are published constitutes acceptance of the revised Terms to the extent permitted by law."] },
  { title: "19. Governing Law", paragraphs: ["These Terms & Conditions shall be governed by the applicable laws of Bangladesh.", "Any dispute arising from the use of our website, products or services shall be subject to the applicable laws and jurisdiction of Bangladesh."] },
  { title: "20. Contact Us", paragraphs: ["For questions regarding these Terms & Conditions, quotations, orders or products, please contact:"], contact: true },
];

export default function TermsPage() {
  return <main className="terms-page">
    <header className="nav"><a className="brand" href="/">Bearing <span>Mart BD</span></a><nav><a href="/about">About</a><a href="/#products">Products</a><a href="/contact">Contact</a></nav><a className="nav-call" href="https://wa.me/8801914528336">WhatsApp Now</a></header>
    <section className="terms-hero"><p className="eyebrow">LEGAL INFORMATION</p><h1>Terms &<br /><em>Conditions.</em></h1><p>Last Updated: August 2026</p></section>
    <section className="terms-content"><p className="terms-intro">Welcome to <strong>Bearing Mart BD</strong>. These Terms & Conditions govern your use of our website, products, quotation services, enquiries, purchases and other services provided by Bearing Mart BD.</p><p className="terms-intro">By accessing or using our website, submitting an enquiry, requesting a quotation, or purchasing products from us, you acknowledge that you have read and agree to these Terms & Conditions.</p>{sections.map((section) => <article className="terms-section" key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}{section.after?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.contact && <address><strong>Bearing Mart BD</strong><br />2nd Floor, Siddique Machinery Market<br />10 Modonpal Lane<br />Dhaka 1100, Bangladesh<br /><br /><strong>Website:</strong> <a href="https://bearingmartbd.com">bearingmartbd.com</a><br /><br />Customers may also contact us through the telephone, WhatsApp or email details published on our official website.</address>}</article>)}</section>
    <footer><span>© {new Date().getFullYear()} Bearing Mart BD</span><a href="/terms">Terms & Conditions</a><span>Quality Bearings, Smooth Solutions</span></footer>
  </main>;
}
