<?php
declare(strict_types=1);
session_start();
require __DIR__ . '/config.php';

if (isset($_GET['logout'])) { session_destroy(); header('Location: admin.php'); exit; }
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['login'])) {
    verify_csrf();
    $user = db()->prepare('SELECT * FROM admins WHERE email = ? LIMIT 1'); $user->execute([strtolower(trim($_POST['email'] ?? ''))]); $user = $user->fetch();
    if ($user && password_verify($_POST['password'] ?? '', $user['password_hash'])) { session_regenerate_id(true); $_SESSION['admin_id'] = $user['id']; header('Location: admin.php'); exit; }
    $error = 'Incorrect email or password.';
}
if (empty($_SESSION['admin_id'])): ?>
<!doctype html><html><head><meta charset="utf-8"><title>Admin sign in</title><link rel="stylesheet" href="style.css"></head><body class="admin-body"><main class="login-card"><h1>Bearing Mart BD</h1><p>Admin panel</p><?php if (!empty($error)): ?><p class="error"><?= $error ?></p><?php endif; ?><form method="post"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="login" value="1"><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" required></label><button>Sign in</button></form></main></body></html><?php exit; endif;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $action = $_POST['action'] ?? '';
    if ($action === 'settings') { foreach (['hero_title','hero_text','phone','address'] as $key) { $stmt=db()->prepare('INSERT INTO settings (`key`,value) VALUES (?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)'); $stmt->execute([$key, trim($_POST[$key] ?? '')]); } }
    if ($action === 'product') { $image=upload_image('image') ?: ''; db()->prepare('INSERT INTO products (name,price,description,image_path) VALUES (?,?,?,?)')->execute([trim($_POST['name']),trim($_POST['price']),trim($_POST['description']),$image]); }
    if ($action === 'slide') { $image=upload_image('image'); if ($image) db()->prepare('INSERT INTO slides (title,subtitle,image_path,sort_order) VALUES (?,?,?,?)')->execute([trim($_POST['title']),trim($_POST['subtitle']),$image,(int)$_POST['sort_order']]); }
    if ($action === 'partner') { $image=upload_image('image') ?: ''; db()->prepare('INSERT INTO partners (name,image_path,website,sort_order) VALUES (?,?,?,?)')->execute([trim($_POST['name']),$image,trim($_POST['website']),(int)$_POST['sort_order']]); }
    if ($action === 'delete' && in_array($_POST['table'] ?? '', ['products','slides','partners'], true)) { db()->prepare('DELETE FROM ' . $_POST['table'] . ' WHERE id = ?')->execute([(int)$_POST['id']]); }
    header('Location: admin.php?updated=1'); exit;
}
$products=db()->query('SELECT * FROM products ORDER BY id DESC')->fetchAll(); $slides=db()->query('SELECT * FROM slides ORDER BY sort_order,id')->fetchAll(); $partners=db()->query('SELECT * FROM partners ORDER BY sort_order,id')->fetchAll();
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bearing Mart BD Admin</title><link rel="stylesheet" href="style.css"></head><body class="admin-body"><header class="admin-header"><strong>Bearing Mart BD · Admin</strong><a href="index.php" target="_blank">View site</a><a href="admin.php?logout=1">Sign out</a></header><main class="dashboard"><?php if (isset($_GET['updated'])): ?><p class="notice">Saved successfully.</p><?php endif; ?>
<section class="panel"><h2>Homepage & contact</h2><form method="post"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="settings"><label>Headline<input name="hero_title" value="<?= htmlspecialchars(setting('hero_title')) ?>"></label><label>Intro text<textarea name="hero_text"><?= htmlspecialchars(setting('hero_text')) ?></textarea></label><label>Phone<input name="phone" value="<?= htmlspecialchars(setting('phone')) ?>"></label><label>Address<textarea name="address"><?= htmlspecialchars(setting('address')) ?></textarea></label><button>Save changes</button></form></section>
<section class="panel"><h2>Add product</h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="product"><label>Name<input name="name" required></label><label>Price / enquiry text<input name="price" placeholder="Call for price"></label><label>Description<textarea name="description"></textarea></label><label>Image<input type="file" name="image" accept="image/jpeg,image/png,image/webp"></label><button>Add product</button></form><div class="items"><?php foreach($products as $item): ?><div><?= htmlspecialchars($item['name']) ?><form method="post"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="table" value="products"><input type="hidden" name="id" value="<?= $item['id'] ?>"><button class="delete">Delete</button></form></div><?php endforeach; ?></div></section>
<section class="panel"><h2>Add slideshow image</h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="slide"><label>Title<input name="title"></label><label>Subtitle<input name="subtitle"></label><label>Display order<input name="sort_order" type="number" value="0"></label><label>Image<input type="file" name="image" accept="image/jpeg,image/png,image/webp" required></label><button>Add slide</button></form><div class="items"><?php foreach($slides as $item): ?><div><?= htmlspecialchars($item['title'] ?: 'Untitled slide') ?><form method="post"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="table" value="slides"><input type="hidden" name="id" value="<?= $item['id'] ?>"><button class="delete">Delete</button></form></div><?php endforeach; ?></div></section>
<section class="panel"><h2>Add partner</h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="partner"><label>Partner name<input name="name" required></label><label>Website URL<input name="website" type="url"></label><label>Display order<input name="sort_order" type="number" value="0"></label><label>Logo<input type="file" name="image" accept="image/jpeg,image/png,image/webp"></label><button>Add partner</button></form><div class="items"><?php foreach($partners as $item): ?><div><?= htmlspecialchars($item['name']) ?><form method="post"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="table" value="partners"><input type="hidden" name="id" value="<?= $item['id'] ?>"><button class="delete">Delete</button></form></div><?php endforeach; ?></div></section></main></body></html>
