<?php
declare(strict_types=1);
require __DIR__ . '/config.php';
$products = db()->query('SELECT * FROM products ORDER BY id DESC')->fetchAll();
$slides = db()->query('SELECT * FROM slides ORDER BY sort_order, id')->fetchAll();
$partners = db()->query('SELECT * FROM partners ORDER BY sort_order, id')->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bearing Mart BD</title><link rel="stylesheet" href="style.css"></head><body>
<header><a class="brand" href="index.php">Bearing <span>Mart BD</span></a><nav><a href="#products">Products</a><a href="#partners">Partnership</a><a href="#contact">Contact</a></nav><a class="call" href="tel:+8801730015018">Call now</a></header>
<section class="hero"><?php if ($slides): $slide=$slides[0]; ?><img src="<?= htmlspecialchars($slide['image_path']) ?>" alt="<?= htmlspecialchars($slide['title']) ?>"><?php endif; ?><div class="hero-copy"><p>ALL KINDS OF BEARING IMPORTER &amp; SUPPLIER</p><h1><?= htmlspecialchars(setting('hero_title', 'Quality Bearings. Smooth Solutions.')) ?></h1><div><?= htmlspecialchars(setting('hero_text')) ?></div><a class="button" href="tel:+8801730015018">Call <?= htmlspecialchars(setting('phone')) ?></a></div></section>
<section id="products" class="section"><p class="label">OUR PRODUCTS</p><h2>Industrial components for every application.</h2><div class="grid"><?php foreach ($products as $product): ?><article class="product"><?php if ($product['image_path']): ?><img src="<?= htmlspecialchars($product['image_path']) ?>" alt="<?= htmlspecialchars($product['name']) ?>"><?php endif; ?><h3><?= htmlspecialchars($product['name']) ?></h3><strong><?= htmlspecialchars($product['price']) ?></strong><p><?= htmlspecialchars($product['description']) ?></p></article><?php endforeach; ?></div></section>
<?php if ($partners): ?><section id="partners" class="partners"><p class="label">PARTNERSHIP</p><div class="partner-grid"><?php foreach ($partners as $partner): ?><a href="<?= htmlspecialchars($partner['website'] ?: '#') ?>"><?php if ($partner['image_path']): ?><img src="<?= htmlspecialchars($partner['image_path']) ?>" alt="<?= htmlspecialchars($partner['name']) ?>"><?php else: ?><?= htmlspecialchars($partner['name']) ?><?php endif; ?></a><?php endforeach; ?></div></section><?php endif; ?>
<section id="contact" class="contact"><div><p class="label">GET IN TOUCH</p><h2>Let&apos;s keep your machines moving.</h2></div><div><h3>Bearing Mart BD</h3><p><?= nl2br(htmlspecialchars(setting('address'))) ?></p><a href="tel:+8801730015018"><?= htmlspecialchars(setting('phone')) ?></a></div></section><footer>© <?= date('Y') ?> Bearing Mart BD · Quality Bearings, Smooth Solutions</footer></body></html>
