CREATE TABLE IF NOT EXISTS admins (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings (`key` VARCHAR(80) PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS products (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(180) NOT NULL, price VARCHAR(100) DEFAULT '', description TEXT DEFAULT '', image_path VARCHAR(255) DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS slides (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(180) DEFAULT '', subtitle VARCHAR(255) DEFAULT '', image_path VARCHAR(255) NOT NULL, sort_order INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS partners (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(180) NOT NULL, image_path VARCHAR(255) DEFAULT '', website VARCHAR(255) DEFAULT '', sort_order INT DEFAULT 0);
