import { env } from "cloudflare:workers";
import Link from "next/link";
import { chatGPTSignInPath,chatGPTSignOutPath,getChatGPTUser } from "../chatgpt-auth";
import "./customer-account.css";

export const dynamic="force-dynamic";
export const metadata={title:"Customer Login | Bearing Mart BD",description:"Secure customer account access for registered Bearing Mart BD customers."};

type Customer={id:string;customerType:string;fullName:string;companyName:string|null;mobile:string;email:string;status:string;createdAt:string};

export default async function CustomerAccountPage(){const user=await getChatGPTUser();let customer:Customer|null=null;if(user){customer=await env.DB.prepare("SELECT id,customer_type AS customerType,full_name AS fullName,company_name AS companyName,mobile,email,status,created_at AS createdAt FROM customers WHERE lower(email)=lower(?)").bind(user.email).first<Customer>()??null}return <main className="customer-account-page"><header className="nav"><Link className="brand" href="/">Bearing <span>Mart BD</span></Link><Link href="/">Return to website</Link></header><section className="customer-account-wrap"><p className="eyebrow">CUSTOMER ACCOUNT</p><h1>{!user?"Customer Login":customer?.status==="verified"?`Welcome, ${customer.fullName}`:"Account Access"}</h1>{!user?<div className="account-card"><h2>Secure customer access</h2><p>Sign in with the same email address used for your Bearing Mart BD customer registration.</p><a className="button primary" href={chatGPTSignInPath("/customer-account")}>Sign in with ChatGPT</a><small>Bearing Mart BD does not store a separate customer password.</small></div>:!customer?<div className="account-card account-notice"><h2>No registration found</h2><p>The signed-in email <strong>{user.email}</strong> is not linked to a customer registration.</p><div className="account-actions"><Link className="button primary" href="/customer-registration">Register as a customer</Link><a className="button secondary" href={chatGPTSignOutPath("/customer-account")}>Use another email</a></div></div>:customer.status!=="verified"?<div className="account-card account-notice"><span className={`account-status ${customer.status}`}>{customer.status.replaceAll("_"," ")}</span><h2>Your registration is awaiting access</h2><p>Your account type is <strong>{customer.customerType==="business"?"Business Customer":"General / Retail Customer"}</strong>. Customer login becomes available after an administrator verifies the registration.</p><p>Registered email: {customer.email}</p><a className="button secondary" href={chatGPTSignOutPath("/")}>Sign out</a></div>:<div className="account-dashboard"><div className="account-summary"><div><span>Access level</span><strong>{customer.customerType==="business"?"Business Customer":"General / Retail Customer"}</strong></div><div><span>Account status</span><strong>Verified</strong></div><div><span>Mobile</span><strong>{customer.mobile}</strong></div></div><div className="account-card"><h2>Your customer dashboard</h2><p>Your account is active. Additional General and Business customer permissions and services can be enabled later by Bearing Mart BD.</p><div className="account-actions"><Link className="button primary" href="/products/ball-bearings/catalog">Browse products</Link><a className="button secondary" href={chatGPTSignOutPath("/")}>Sign out</a></div></div></div>}</section></main>}
