import Link from "next/link";
import { headers } from "next/headers";
import { getCustomerFromSession } from "../customer-auth";
import CustomerLoginForm from "./login-form";
import LogoutButton from "./logout-button";
import "./customer-account.css";

export const dynamic="force-dynamic";
export const metadata={title:"Customer Login | Bearing Mart BD",description:"Secure customer account access for registered Bearing Mart BD customers."};

export default async function CustomerAccountPage(){const requestHeaders=await headers(),customer=await getCustomerFromSession(requestHeaders.get("cookie"));return <main className="customer-account-page"><header className="nav"><a className="brand" href="https://bearingmartbd.com/">Bearing <span>Mart BD</span></a><a href="https://bearingmartbd.com/">Return to website</a></header><section className="customer-account-wrap"><p className="eyebrow">CUSTOMER ACCOUNT</p><h1>{customer?`Welcome, ${customer.fullName}`:"Customer Login"}</h1>{!customer?<div className="account-card"><h2>Secure customer access</h2><p>Use the email address or mobile number and password created during registration.</p><CustomerLoginForm/><div className="account-register-note"><span>Not registered yet?</span><Link href="/customer-registration">Create a customer account</Link></div></div>:customer.status!=="verified"?<div className="account-card account-notice"><span className={`account-status ${customer.status}`}>{customer.status.replaceAll("_"," ")}</span><h2>Account access is unavailable</h2><p>Please contact Bearing Mart BD if you believe this status should be reviewed.</p><LogoutButton/></div>:<div className="account-dashboard"><div className="account-summary"><div><span>Access level</span><strong>{customer.customerType==="business"?"Business Customer":"General / Retail Customer"}</strong></div><div><span>Account status</span><strong>Verified</strong></div><div><span>Mobile</span><strong>{customer.mobile}</strong></div></div><div className="account-card"><h2>Your customer dashboard</h2><p>Your account is active. Additional General and Business customer permissions and services can be enabled later by Bearing Mart BD.</p><div className="account-actions"><a className="button primary" href="https://bearingmartbd.com/products/ball-bearings/catalog">Browse products</a><LogoutButton/></div></div></div>}</section></main>}
